In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

generated_inputs = np.column_stack((xs,zs))

noise = np.random.uniform(-1, 1, (observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)

In [3]:
training_data=np.load('TF_intro.npz')

In [4]:
input_size=2
output_size=1

In [5]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(output_size,
                         kernel_initializer=tf.keras.initializers.RandomUniform(minval=-0.1, maxval=0.1),
                         bias_initializer=tf.keras.initializers.RandomUniform(minval=-0.1, maxval=0.1))
])

customize_model=tf.keras.optimizers.SGD(learning_rate=0.02)

model.compile(optimizer=customize_model,loss='mean_squared_error')

model.fit(training_data['inputs'],training_data['targets'],epochs=100,verbose=2)

Train on 1000 samples
Epoch 1/100
1000/1000 - 0s - loss: 21.2498
Epoch 2/100
1000/1000 - 0s - loss: 1.1078
Epoch 3/100
1000/1000 - 0s - loss: 0.4380
Epoch 4/100
1000/1000 - 0s - loss: 0.3778
Epoch 5/100
1000/1000 - 0s - loss: 0.3683
Epoch 6/100
1000/1000 - 0s - loss: 0.4779
Epoch 7/100
1000/1000 - 0s - loss: 0.3757
Epoch 8/100
1000/1000 - 0s - loss: 0.3778
Epoch 9/100
1000/1000 - 0s - loss: 0.3878
Epoch 10/100
1000/1000 - 0s - loss: 0.4163
Epoch 11/100
1000/1000 - 0s - loss: 0.4208
Epoch 12/100
1000/1000 - 0s - loss: 0.3781
Epoch 13/100
1000/1000 - 0s - loss: 0.3817
Epoch 14/100
1000/1000 - 0s - loss: 0.4111
Epoch 15/100
1000/1000 - 0s - loss: 0.3794
Epoch 16/100
1000/1000 - 0s - loss: 0.3958
Epoch 17/100
1000/1000 - 0s - loss: 0.4257
Epoch 18/100
1000/1000 - 0s - loss: 0.3982
Epoch 19/100
1000/1000 - 0s - loss: 0.4123
Epoch 20/100
1000/1000 - 0s - loss: 0.4402
Epoch 21/100
1000/1000 - 0s - loss: 0.4068
Epoch 22/100
1000/1000 - 0s - loss: 0.3895
Epoch 23/100
1000/1000 - 0s - loss: 0.41

In [6]:
model.layers[0].get_weights()

[array([[ 2.0114672],
        [-3.074689 ]], dtype=float32),
 array([5.010852], dtype=float32)]

In [7]:
model.predict_on_batch(training_data['inputs'])

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[ 3.72491302e+01],
       [-4.60793018e+00],
       [-2.43716278e+01],
       [ 8.86084080e-01],
       [-8.82546329e+00],
       [-2.62336922e+01],
       [-6.54278278e+00],
       [ 2.34880543e+00],
       [-2.96335983e+00],
       [ 1.87503967e+01],
       [-1.41547632e+01],
       [-1.58983908e+01],
       [ 3.03314972e+01],
       [-6.81201077e+00],
       [-5.58577538e-01],
       [-9.57443237e+00],
       [ 6.02636909e+00],
       [ 2.21515656e+01],
       [ 2.61997185e+01],
       [-4.82652760e+00],
       [ 3.09031181e+01],
       [-4.10309258e+01],
       [-8.83136940e+00],
       [ 9.09042168e+00],
       [ 2.80379486e+01],
       [ 1.52925272e+01],
       [ 2.97296219e+01],
       [ 1.87007856e+00],
       [ 3.44491386e+00],
       [ 3.49443855e+01],
       [-1.18142462e+01],
       [-3.79157753e+01],
       [-1.20838022e+01],
       [ 2.74707413e+01],
       [ 1.14709568e+00],
       [ 1.29530249e+01],
       [ 2.36

In [8]:
training_data['targets'].round(1)

array([[ 37. ],
       [ -4.7],
       [-24.4],
       [  0.5],
       [ -8.3],
       [-25.8],
       [ -5.9],
       [  2.1],
       [ -2.6],
       [ 18.5],
       [-12.6],
       [-15.1],
       [ 30. ],
       [ -5.4],
       [ -0.3],
       [ -9.8],
       [  6.7],
       [ 22. ],
       [ 25.4],
       [ -5.3],
       [ 31. ],
       [-40.3],
       [ -8. ],
       [  8.2],
       [ 28.1],
       [ 14.7],
       [ 30.3],
       [  2. ],
       [  3.1],
       [ 34.8],
       [-11.9],
       [-37.7],
       [-12.3],
       [ 25.9],
       [  1.1],
       [ 12.3],
       [ 23.5],
       [  7.4],
       [ 36.6],
       [ -0.5],
       [ -8.1],
       [ 18.2],
       [  6.4],
       [-15.4],
       [ 27.4],
       [  5. ],
       [ 18.1],
       [ -2.8],
       [-20.2],
       [ 38.2],
       [ -3.1],
       [ 18.4],
       [ 22.6],
       [ 44.4],
       [ -5.7],
       [ -1. ],
       [ 33.4],
       [ 12.4],
       [ 12.9],
       [ 13.6],
       [-11.5],
       [ 20.2],
       [